var option;
option = "<option value='กระบี่'>กระบี่</option>"
option += "<option value=' กรุงเทพมหานคร'>กรุงเทพมหานคร</option>"
option += "<option value='กาญจนบุรี'> กาญจนบุรี </option>"
option += "<option value='กาฬสินธุ์'>กาฬสินธุ์</option>"
option += "<option value=' กำแพงเพชร'>กำแพงเพชร</option>"
option += "<option value='ขอนแก่น'> ขอนแก่น </option>"
option += "<option value='จันทบุรี'>จันทบุรี</option>"
option += "<option value=' ฉะเชิงเทรา'>ฉะเชิงเทรา</option>"
option += "<option value='ชลบุรี'> ชลบุรี </option>"
option += "<option value='ชัยนาท'>ชัยนาท</option>"
option += "<option value=' ชัยภูมิ'>ชัยภูมิ</option>"
option += "<option value='ชุมพร'> ชุมพร</option>"
option += "<option value='เชียงราย'>เชียงราย</option>"
option += "<option value=' เชียงใหม่'>เชียงใหม่</option>"
option += "<option value='ตรัง'>    ตรัง </option>"
option += "<option value='ตราด'>ตราด</option>"
option += "<option value=' ตาก'>ตาก</option>"
option += "<option value='นครนายก'> นครนายก </option>"
option += "<option value='นครปฐม'>นครปฐม</option>"
option += "<option value=' นครพนม'>นครพนม</option>"
option += "<option value='นครราชสีมา'>    นครราชสีมา </option>"
option += "<option value='นครศรีธรรมราช'>นครศรีธรรมราช</option>"
option += "<option value=' นครสวรรค์'>นครสวรรค์</option>"
option += "<option value='นนทบุรี'> นนทบุรี </option>"
option += "<option value='นราธิวาส'>นราธิวาส</option>"
option += "<option value=' น่าน'>น่าน</option>"
option += "<option value='บุรีรัมย์'>    บุรีรัมย์ </option>"
option += "<option value='ปทุมธานี'>ปทุมธานี</option>"
option += "<option value=' ประจวบคีรีขันธ์'>ประจวบคีรีขันธ์</option>"
option += "<option value='ปราจีนบุรี'> ปราจีนบุรี </option>"
option += "<option value='ปัตตานี'>ปัตตานี</option>"
option += "<option value=' พระนครศรีอยุธยา'>พระนครศรีอยุธยา</option>"
option += "<option value='พะเยา'> พะเยา </option>"
option += "<option value='พังงา'>พังงา</option>"
option += "<option value=' พัทลุง'>พัทลุง</option>"
option += "<option value='พิจิตร'> พิจิตร</option>"
option += "<option value='พิษณุโลก'>พิษณุโลก</option>"
option += "<option value=' เพชรบุรี'>เพชรบุรี</option>"
option += "<option value='เพชรบูรณ์'> เพชรบูรณ์ </option>"
option += "<option value='แพร่'>แพร่</option>"
option += "<option value=' ภูเก็ต'>ภูเก็ต</option>"
option += "<option value='มหาสารคาม'>    มหาสารคาม </option>"
option += "<option value='มุกดาหาร'>มุกดาหาร</option>"
option += "<option value=' แม่ฮ่องสอน'>แม่ฮ่องสอน</option>"
option += "<option value='ยโสธร'> ยโสธร </option>"
option += "<option value='ยะลา'>ยะลา</option>"
option += "<option value=' ร้อยเอ็ด'>ร้อยเอ็ด</option>"
option += "<option value='ระนอง'> ระนอง</option>"
option += "<option value='ระยอง'>ระยอง</option>"
option += "<option value=' ราชบุรี'>ราชบุรี</option>"
option += "<option value='ลพบุรี'> ลพบุรี</option>"
option += "<option value='เลย'>เลย</option>"
option += "<option value=' ลำปาง'>ลำปาง</option>"
option += "<option value='ลำพูน'> ลำพูน </option>"
option += "<option value='ศีรสะเกษ'>ศีรสะเกษ</option>"
option += "<option value=' สกลนคร'>สกลนคร</option>"
option += "<option value='สงขลา'>    สงขลา </option>"
option += "<option value='สตูล'>สตูล</option>"
option += "<option value=' สมุทรปราการ'>สมุทรปราการ</option>"
option += "<option value='สมุทรสงคราม'> สมุทรสงคราม </option>"
option += "<option value='สมุทรสาคร'>สมุทรสาคร</option>"
option += "<option value=' สระแก้ว'>สระแก้ว</option>"
option += "<option value='สระบุรี'>    สระบุรี </option>"
option += "<option value='สิงห์บุรี'>สิงห์บุรี</option>"
option += "<option value=' สุโขทัย'>สุโขทัย</option>"
option += "<option value='สุพรรณบุรี'> สุพรรณบุรี </option>"
option += "<option value='สุราษฎร์ธานี'>สุราษฎร์ธานี</option>"
option += "<option value=' สุรินทร์'>สุรินทร์</option>"
option += "<option value='หนองคาย'> หนองคาย </option>"
option += "<option value='หนองบัวลำภู'>หนองบัวลำภู</option>"
option += "<option value=' อ่างทอง'>อ่างทอง</option>"
option += "<option value='อำนาจเจริญ'> อำนาจเจริญ </option>"
option += "<option value='อุดรธานี'>อุดรธานี</option>"
option += "<option value=' อุตรดิตถ์'>อุตรดิตถ์</option>"
option += "<option value='อุทัยธานี'> อุทัยธานี </option>"
option += "<option value='อุบลราชธานี'>อุบลราชธานี</option>"

$('#province').append(option)